# Site settings
title: YJ's Dev Blog
author: YJ
email: your-email@example.com
description: >-
  기술 블로그 | Tech Blog
baseurl: ""
url: "https://yunjeongiya.github.io"

# Build settings
markdown: kramdown
remote_theme: yous/whiteglass

# Plugin settings
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-archives

# Whiteglass theme settings
lang: ko
navigation:
  - title: Home
    url: /
  - title: Archives
    url: /archives/
  - title: About
    url: /about/

# Archives
jekyll-archives:
  enabled:
    - categories
    - tags
  layout: category_archives
  permalinks:
    category: /categories/:name/
    tag: /tags/:name/

# Multi-language support
languages: ["ko", "en"]
default_lang: "ko"

# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      lang: "ko"

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md
