# Site settings
title: YJ's Dev Blog
author: YJ
email: your-email@example.com
description: >-
  기술 블로그 | Tech Blog
baseurl: ""
url: "https://yunjeongiya.github.io"

# Build settings
markdown: kramdown
theme: minima

# Plugin settings
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Minima settings
minima:
  skin: dark

# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md
