# Site settings
title: Yunjeong Luna Lee | Dev Blog
author: Yunjeong Luna Lee
email: your-email@example.com
description: >-
  기술 블로그 | Tech Blog
baseurl: ""
url: "https://yunjeongiya.github.io"

# Build settings
markdown: kramdown
theme: minima

# Plugin settings
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Minima settings
minima:
  skin: dark

# Permalink structure
permalink: /:categories/:year/:month/:day/:title/

# Defaults
defaults:
  # Korean posts (default)
  - scope:
      path: "_posts/ko"
      type: "posts"
    values:
      layout: "post"
      lang: "ko"

  # English posts (with /en/ prefix)
  - scope:
      path: "_posts/en"
      type: "posts"
    values:
      layout: "post"
      lang: "en"
      permalink: "/en/:categories/:year/:month/:day/:title/"

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md
  - .claude
  - CLAUDE.md
  - BLOG_DEVELOPMENT.md
